// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath(libs.android.plugin.gradle)
        classpath(libs.kotlin.plugin.gradle)
        classpath(libs.spotless.plugin.gradle)
        classpath(libs.hilt.plugin.gradle)
        classpath(libs.ksp.plugin.gradle)
    }
}

apply plugin: "com.diffplug.spotless"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

spotless {
    ratchetFrom 'origin/main'
    format 'misc', {
        target '**/*.gradle', '**/*.md', '**/.gitignore'
        trimTrailingWhitespace()
        indentWithSpaces()
        endWithNewline()
    }
    format 'xml', {
        target '**/*.xml'
        trimTrailingWhitespace()
        indentWithSpaces()
        endWithNewline()
    }
    kotlin {
        target '**/src/**/*.kt'
        ktlint(libs.versions.ktlint.get())
        licenseHeaderFile rootProject.file('spotless/copyright.kt')
    }
}
